CREATE TABLE drill_operations (
    id BIGSERIAL PRIMARY KEY,
    worker_email VARCHAR(255),
    worker_name VARCHAR(255),
    site VARCHAR(255),
    zone VARCHAR(255),
    equipment_code VARCHAR(100),
    drill_type VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS',
    step_setup_complete BOOLEAN DEFAULT FALSE,
    step_setup_at TIMESTAMP,
    step_setup_notes TEXT,
    step_drilling_complete BOOLEAN DEFAULT FALSE,
    step_drilling_at TIMESTAMP,
    step_drilling_notes TEXT,
    step_blasting_complete BOOLEAN DEFAULT FALSE,
    step_blasting_at TIMESTAMP,
    step_blasting_notes TEXT,
    step_cleanup_complete BOOLEAN DEFAULT FALSE,
    step_cleanup_at TIMESTAMP,
    step_cleanup_notes TEXT,
    started_at TIMESTAMP NOT NULL DEFAULT now(),
    completed_at TIMESTAMP
);
